### PR TITLE
Add fileCache (copy of PR #94).

### PR DESCRIPTION
**Pull request by ohjames**

### CODE REVIEW

**Comment by ohjames** [comment]
Reference! https://github.com/substack/module-deps/pull/94 - :baby_chick:

**Comment by zertosh** [comment]
Thanks!

**Comment by zertosh** [comment]
published as module-deps@3.9.0.

For those reading this PR: The reason why replacing `this.cache` with `this.fileCache` in `readFile` is not a breaking change is because it hasn't worked (ever?). When a file is in `this.cache`, `readFile` is never called.

**Comment by ohjames** [comment]
@zertosh Thanks for being so patient with all your help! My brain is a fog, I'm going back to sleep for a day or two ;)

**Comment by zanona** [comment]
one question, I have been trying like crazy to use `fileCache` option on browserify. Bottom line, it didn't work at all. Then I decided to do a few tests with module-deps itself and run the test attached to this PR. under version 4.0.7 and unfortunately it didn't work as well:

```
TAP version 13
# Subtest: uses file cache
    1..1
    not ok 1 - Error: Cannot find module '/Users/zanona/Developer/libs/pakku/files/foo.js' from '/Users/zanona/Developer/libs/pakku'
      ---
      at:
        line: 55
        column: 21
        file: node_modules/resolve/lib/async.js
      stack: |
        node_modules/resolve/lib/async.js:55:21
        load (node_modules/resolve/lib/async.js:69:43)
        onex (node_modules/resolve/lib/async.js:92:31)
        node_modules/resolve/lib/async.js:22:47
        FSReqWrap.oncomplete (fs.js:82:15)
      test: uses file cache
      message: >-
        Error: Cannot find module '/Users/zanona/Developer/libs/pakku/files/foo.js'
        from '/Users/zanona/Developer/libs/pakku'
      source: |
        else cb(new Error("Cannot find module '" + x + "' from '" + y + "'"))
      ...
    # failed 1 of 1 tests
not ok 1 - uses file cache # time=35.27ms
  ---
  at:
    line: 24
    column: 1
    file: node.js
  results:
    plan:
      start: 1
      end: 1
    count: 1
    pass: 0
    ok: false
    fail: 1
    time: 35.27
  source: |
    test('uses file cache', function (t) {
  ...

1..1
# failed 1 of 1 tests
# time=64.338ms
```

any ideas? I would imagine this would be something public by now but still not sure.
Thanks

**Pull request merged**
